// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrM_qTSMS1BecbtfS45cLaJ6NOpqtIbts',
    appId: '1:145504042752:web:bda144116b993dbb56bde5',
    messagingSenderId: '145504042752',
    projectId: 'pgh-bible-reading-plan',
    authDomain: 'pgh-bible-reading-plan.firebaseapp.com',
    databaseURL: 'https://pgh-bible-reading-plan.firebaseio.com',
    storageBucket: 'pgh-bible-reading-plan.firebasestorage.app',
    measurementId: 'G-2Y6XRG7EZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PCZFDnOqKIygrp2L0EhaFCCpSEpIWYY',
    appId: '1:145504042752:android:dc622c11a88c748856bde5',
    messagingSenderId: '145504042752',
    projectId: 'pgh-bible-reading-plan',
    databaseURL: 'https://pgh-bible-reading-plan.firebaseio.com',
    storageBucket: 'pgh-bible-reading-plan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-LWXVDDYAJvCHMx9FDJm_HFjvR84ro8',
    appId: '1:145504042752:ios:9969d0e0b758a1d056bde5',
    messagingSenderId: '145504042752',
    projectId: 'pgh-bible-reading-plan',
    databaseURL: 'https://pgh-bible-reading-plan.firebaseio.com',
    storageBucket: 'pgh-bible-reading-plan.firebasestorage.app',
    androidClientId: '145504042752-89rv9d2solbcom0sfk746rd9j4qv6v8j.apps.googleusercontent.com',
    iosClientId: '145504042752-o1l37m6uanjt4fpv6a4dep2aob75jqoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unquenchedBible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-LWXVDDYAJvCHMx9FDJm_HFjvR84ro8',
    appId: '1:145504042752:ios:9969d0e0b758a1d056bde5',
    messagingSenderId: '145504042752',
    projectId: 'pgh-bible-reading-plan',
    databaseURL: 'https://pgh-bible-reading-plan.firebaseio.com',
    storageBucket: 'pgh-bible-reading-plan.firebasestorage.app',
    androidClientId: '145504042752-89rv9d2solbcom0sfk746rd9j4qv6v8j.apps.googleusercontent.com',
    iosClientId: '145504042752-o1l37m6uanjt4fpv6a4dep2aob75jqoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unquenchedBible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnU6Hp0M4ITZ_C7y_O-CAEVHqon2XiZYA',
    appId: '1:145504042752:web:17446876f1eccab956bde5',
    messagingSenderId: '145504042752',
    projectId: 'pgh-bible-reading-plan',
    authDomain: 'pgh-bible-reading-plan.firebaseapp.com',
    databaseURL: 'https://pgh-bible-reading-plan.firebaseio.com',
    storageBucket: 'pgh-bible-reading-plan.firebasestorage.app',
    measurementId: 'G-KV5Y05FS66',
  );
}
